packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  '@tailwindcss/vite': ^4.0.6
  '@tanstack/eslint-config': ^0.3.0
  '@tanstack/react-devtools': ^0.2.2
  '@tanstack/react-router': ^1.130.2
  '@tanstack/react-router-devtools': ^1.131.5
  '@tanstack/router-plugin': ^1.121.2
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.2.0
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@vitejs/plugin-react': ^4.3.4
  autoprefixer: ^10.4.0
  class-variance-authority: ^0.7.0
  clsx: ^2.0.0
  eslint: ^8.57.0
  jsdom: ^26.0.0
  lucide-react: ^0.294.0
  postcss: ^8.4.0
  prettier: ^3.5.3
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwind-merge: ^2.0.0
  tailwindcss: ^4.0.6
  tailwindcss-animate: ^1.0.7
  typescript: ^5.7.2
  vite: ^6.3.5
  vitest: ^3.0.5
  web-vitals: ^4.2.4
catalogs:
  conflicts_@tailwindcss/vite_h4_1_12:
    '@tailwindcss/vite': ^4.1.12
